on:
  push:
    branches: [main, master]
    tags: ['*']

name: "Build Slides"

jobs:
  build_slides:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: tomjemmett/renv-install-system-deps@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-renv@v1

      - name: Get icons
        uses: tomjemmett/setup-r-icons@v1
        with:
          icon-sets: fontawesome

      - name: Build slides
        run: make

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
